import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Layout from "@/assets/js/layout";
import { useState } from "react";

export default function Home() {
  const [expression, setExpression] = useState(null);
  const [result, setResult] = useState(null);

  return (
    <Layout>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.calculator}>
        <div className={styles.content}>
          <div className={styles.header}>
            <div className={`${styles.visor} grid`}>
              <input type="text" value={expression} readOnly />
              <input type="text" value={result} readOnly />
            </div>
          </div>

          <div className={styles.middle}>
            <div className={`grid ${styles.content}`}>
              <button>AC</button>
              <button>Delete</button>
              <button>%</button>
              <button>/</button>
              <button>1</button>
              <button>2</button>
              <button>3</button>
              <button>X</button>
              <button>4</button>
              <button>5</button>
              <button>6</button>
              <button>-</button>
              <button>7</button>
              <button>8</button>
              <button>9</button>
              <button>+</button>
              <button>0</button>
              <button>,</button>
              <button>=</button>
            </div>
          </div>

          <div className={styles.footer}></div>
        </div>
      </div>
    </Layout>
  );
}
